export const CHANGE_CATEGORY = "CHANGE_CATEGORY"

export const GET_CATEGORIES_START = "GET_CATEGORIES_START"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const REMOVE_PRODUCT_FROM_LIST = "REMOVE_PRODUCT_FROM_LIST";
export const REMOVE_PRODUCT_FROM_LIST_ERROR = "REMOVE_PRODUCT_FROM_LIST_ERROR";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"